name: Request
on:
  issues:
    types:
      - opened
  issue_comment:
    types:
      - created
env:
  TZ: 'Asia/Tokyo'
jobs:
  register:
    runs-on: ubuntu-22.04
    if: |
      (github.event_name == 'issues') || (
        github.event_name == 'issue_comment' &&
        !github.event.issue.pull_request &&
        startsWith(github.event.comment.body, '/retry') &&
        (github.actor == github.event.issue.user.login)
      )
    steps:
      - name: Add Reaction (for registration)
        if: github.event_name == 'issues'
        run: |
          gh api -X POST repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/reactions -f content=+1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Add Reaction (for retry request)
        if: github.event_name == 'issue_comment'
        run: |
          gh api -X POST repos/${{ github.repository }}/issues/comments/${{ github.event.comment.id }}/reactions -f content=+1
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.4.1
      - name: Setup Nodejs
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Install Chromium
        run: pnpm playwright install chromium --with-deps
      - name: Run
        run: pnpm start
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit Leaderboard
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"